version: '3.2'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "set -x; cd /opt/api; while true; do python app.py; done;"
    container_name: poc-api
    depends_on:
      - apidb
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      PORT: 80
      PYTHONPATH: /opt/api
      SQLALCHEMY_DATABASE_URI: postgresql://poc-user:poc-password@apidb/poc-emmental
    networks:
      - joint
    ports:
      - 80:80
    volumes:
      - ./api:/opt/api
      - ./docker_data/apidb:/var/lib/postgresql/data
    restart: always
    
  apidb:
    # command: *TBW*
    container_name: poc-apidb
    environment:
        - POSTGRES_DB=poc-emmental
        - POSTGRES_USER=poc-user
        - POSTGRES_PASSWORD=poc-password
    image: postgres:10.1
    networks:
      - joint
    volumes:
      - ./docker_data/apidb:/var/lib/postgresql/data
    restart: always

networks:
  joint:
    driver: bridge

volumes:
  api:
  docker_data:
